# Generated by Django 3.1.3 on 2021-01-08 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='is_available',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='last_donation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DonationModel',
        ),
    ]
